// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef xedt_h
#define xedt_h
#include <FL/Fl.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Text_Editor.H>
extern Fl_Text_Editor *tag_data;
Fl_Double_Window* edit_window();

class XTree : virtual public Fl_Tree {
public:
  XTree(int x, int y, int w, int h ) ;
  int handle(int e);
};
#include <FL/Fl_Button.H>
extern Fl_Button *open;
Fl_Double_Window* make_window();
#endif
